path_classifiers:
  library:
    - third_party/lit
    - third_party/musl
  docs:
    - README.md
    - LICENSE.txt
    - CREDITS.txt
    - docs/*md
  test:
    - test/lit

extraction:
  cpp:
    prepare:
      packages:
        - llvm-4.0-dev
        - llvm-4.0-tools
        - llvm-4.0
        - llvm-4.0-runtime
        - texlive-latex-recommended
      
    configure:
      command:
        - mkdir -p _lgtm_build_dir
        - cd _lgtm_build_dir
        # Kludge LLVM_DIR so LGTM's autobuild doesn't get confused and install all LLVM versions
        - cmake .. -DBUILD_DOCS=OFF -DCMAKE_BUILD_TYPE=Release -DLLVM_DIR=/usr/lib/llvm-4.0/lib/cmake/llvm
