path_classifiers:
  library:
    - utils/lit
    - libs/none/musl
  docs:
    - README.md
    - LICENSE.txt
    - CREDITS.txt
    - docs/*md
  test:
    - test/lit

extraction:
  cpp:
    prepare:
      packages:
        - llvm-4.0-dev
        - llvm-4.0-tools
          # TODO: liblld needed for alld
        # - liblld-4.0-dev
