language: nix
nix: 2.1.2

before_install:
  - ./.travis/configure-nix.sh
  - ./.travis/install-cachix.sh

# Force VM instead of container, so that sandbox works
sudo: required

# CACHIX_SIGNING_KEY
env:
  global:
    secure: c+MlrvnlkujwO+xeTpDIhCbJdayIsfpWeqPzZl4g5pqAVMMPltaSMSIlxYaRiGzF77IrLi1slSyXVUl4jWTYMyUpCnfKaI+L9joiOQjuoTl7j4slO7aIzx2LGCvM8Drj9PYSR+RCkZiPjbusnd/ABr638gymNn9o9HNkArdW7rzg+w7PcaDcB67t/MHGfjwcD1mX+rws89eDujaif3ZSy1PXqOHb3hKn11aeGxAT96PKNlazAjBMmISn+ScKfUL292SOTW+XPATDLYtMkyVrV6QE4/0Syum3fCSrBY44LQxmBPzE4RAt8m9IPGURc84+l6bdP/WR1IrBZZ8fPLVZVERLplJSMtRi5FpeUfkQiMEkb4gm+kQ/mIpkpbXxWtAuOMr+vafmJrv4ILG07N0YHB+n4l073MXtwv8CIYF4fZVTji56VOKn7d3mFdrGGLMJb4LZf5Aa3CH23MLYUYTlEN7rOgU+LWhJ2EdTiUwjw+xcYwzm6mOm5Mz2IEjSNWX1YirvXYUhIJ3JRSwbsi/96g88mWE3WJ5wWdmRK33+0HInxz9S5rjYW2lBa+0+ZR0ubOu48I8ekihzpR4jjpo4RVW85wSOfFcwl/3HY+vxdXV3z45tdgGP8ykZ4WsLfRs+gOOXMOaRZ7fvSNt4FWkGqYeVqpw0VI6ZwW3Mtr3LnI4=
  matrix:
    - FILE=./default.nix
    - FILE=./nix/release.nix ATTR=default
    - FILE=./nix/release.nix ATTR=musl

# Full clone
git:
  depth: false

script:
  - ./.travis/build.sh ${FILE:-./default.nix} ${ATTR:+-A $ATTR}
