#!/usr/bin/env python3

import argparse
import os
import zipfile

def make_archive(bitcode, output):
    if not output:
        output = os.path.splitext(bitcode.name)[0] + ".allexe"

    # Open a new zip file for writing. Disallow ZIP64 extensions, and default to
    # using DEFLATE compression (neither of these are Python's defaults).
    with zipfile.ZipFile(output, 'w', zipfile.ZIP_DEFLATED, False) as allzip:
        # Add the main.bc as the first entry in the archive.
        allzip.write(bitcode.name, "main.bc")


parser = argparse.ArgumentParser(
    description="Convert a .bc file into a .allexe container")
parser.add_argument("bitcode", metavar="main.bc", type=argparse.FileType('rb'),
    help="Bitcode file to use as the main file")
parser.add_argument("-o", metavar="output", dest="output",
    help="Program filename to write out to")
args = parser.parse_args()

make_archive(args.bitcode, args.output)
