name: "Test"
on: [push, pull_request]

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v12
    - uses: cachix/cachix-action@v6
      with:
        name: allvm
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build
  compiler-tests:
    needs: default
    strategy:
      matrix:
       variant: [default, musl.allvm-tools, musl.allvm-tools-gcc9]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v12
    - uses: cachix/cachix-action@v6
      with:
        name: allvm
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build nix/release.nix -A '${{ matrix.variant }}'
