name: "Test"
on: [push, pull_request]

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v3
    - uses: cachix/cachix-action@v2
      with:
        name: allvm
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
  compiler-tests:
    needs: default
    strategy:
      matrix:
       variant: [default, musl]
       compiler: [clang4, clang5, clang6, clang7, clang8, clang9, gcc7, gcc8, gcc9]
      max-parallel: 2
    runs-on: ubuntu-latest
    name: Build+Test using toolchain ${{ matrix.variant }} ${{ matrix.compiler }}
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v3
    - uses: cachix/cachix-action@v2
      with:
        name: allvm
        file: nix/release.nix 
        attributes: '${{ matrix.variant }}.allvm-tools-${{ matrix.compiler }}'
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
