name: "Test"
on: [push, pull_request]

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v11
      with:
        skip_adding_nixpkgs_channel: true
    - name: Print nix config
      run: nix show-config
    - uses: cachix/cachix-action@v5
      with:
        name: allvm
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
  compiler-tests:
    needs: default
    strategy:
      matrix:
       variant: [default, musl]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v11
      with:
        skip_adding_nixpkgs_channel: true
    - uses: cachix/cachix-action@v5
      with:
        name: allvm
        file: nix/release.nix 
        attributes: '${{ matrix.variant }}'
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
